import { Button, VerticalBox, ListView, CheckBox, LineEdit } from "std-widgets.slint";

struct TodoItem{
    text: string, 
    checked: bool,
}
export component AppWindow inherits Window {
    in property <[TodoItem]> todos;
    callback add-todo(string);

    min-width: 300px;
    title: "Todo List";

    VerticalBox {
        HorizontalLayout {
            spacing: 4px;
            le := LineEdit {
                placeholder-text: "Todo";
            }
            Button {
                text: "Add";
                clicked => {
                    // Call the callback to add a new todo item
                    root.add-todo(le.text)
                }   
            }
        }
        ListView{
            for todo in root.todos:
                CheckBox {
                    text: todo.text;
                    checked: todo.checked;
                }
        }        
    }    
}