import { LineEdit, Button, VerticalBox, StandardButton } from "std-widgets.slint";
export component AppWindow inherits Window {
    in property <string> results: "";
    callback divide-income(string);
    in-out property <bool> open_curtain;
    animate background { duration: 800ms; }

    MenuBar {
        Menu {
            title: @tr("File");
            MenuItem {
                title: @tr("New");
                activated => { file-new(); }
            }
            MenuItem {
                title: @tr("Open");
                activated => { file-open(); }
            }
        }
        Menu {
            title: @tr("Edit");
            MenuItem {
                title: @tr("Copy");
            }
            MenuItem {
                title: @tr("Paste");
            }
            MenuSeparator {}
            Menu {
                title: @tr("Find");
                MenuItem {
                    title: @tr("Find in document...");
                }
                MenuItem {
                    title: @tr("Find Next");
                }
                MenuItem {
                    title: @tr("Find Previous");
                }
            }
        }
    }
    callback file-new();
    callback file-open();

    // ... actual window content goes here
        background: #313e50;

    GridLayout {

    export component Example inherits Dialog {
        Text {
        text: "This is a dialog box";
        }
        StandardButton { kind: ok; }
        StandardButton { kind: cancel; }
        Button {
        text: "More Info";
        dialog-button-role: action;
        }
}
    }
}